

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'swiper/css';
import 'swiper/css/effect-cards'
import {NextUIProvider} from '@/app/client/next'
import Header from './components/header';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir='rtl' className='bg-black'>
      <body className='dark container mx-auto bg-black'>
        <Header/>
        <NextUIProvider>
          {children}
        </NextUIProvider>
      </body>
    </html>
  )
}
